### ISSUE TITLE
problem with version 0.78 - UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by darthcoli** [sshuttle/sshuttle#110]
I installed from pip the version 0.78 and with some ubuntu systems (as far as I can test),  can't create the tunnel, I got the error: 
"UnicodeDecodeError: 'ascii' codec can't decode byte"

In the target machine the "netstat -rn" output is correct. 

If I install the package from the official repo (in my debian jessie is the 0.52 and in ubuntu 16.04 is the 0.71) the tunnel is created without issues. So I suspect that the version 0.78 maybe have some bug. 
Regards

**Comment by brianmay** [comment]
Probably need a new release sometime. I believe this is fixed in git.

**Comment by brianmay** [comment]
Should be fixed in 0.78.1 which I just released.

**Comment by AladW** [comment]
Still seeing this issue on git master. Is there a reason for using ascii, instead of utf8?

**Comment by brianmay** [comment]
It sounds like this could be a different bug report. Please create a new bug report and include the full stack trace (if available).

Also I believe that "netstat" should only ever return ASCII data. It would be highly unusual if this was not the case I think.
