### ISSUE TITLE
sshuttle doesn't hide my IPV6 address

### ISSUE THREAD

**Issue by naclander** [sshuttle/sshuttle#45]
I've been using sshuttle for a number of years now, and recently my ISP rolled out IPV6 support. 
The sshuttle command I use is:

    sshuttle --no-latency-control -vvr username@remote.server 0/0 -x 10.0.0.0/24

Sometimes I add the ````--dns```` flag as well.

This has been working fine, and continuous to work fine, for sites that show me an IPV4 address. For example, http://www.whatsmyip.org/ correctly shows me remote.server's address, instead of my real one. And I see what looks like correct activity from the sshuttle debug output.

However I've recently noticed that sites responding back with an IPV6 (have IPV6 support?) are still showing me my real IPV6 address. For example:

    https://www.google.com/search?q=google+what%27s+my+ip&ie=utf-8&oe=utf-8
    icanhazip.com

When accessing those sites or downloading anything from them I see no output from sshuttle, which makes me suspect sshuttle is getting bypassed somehow and doesn't intercept the IPV6 traffic (although I am just guessting). 
Furthermore if the ````--dns```` flag is used I do see the dns query go through for those sites, just not the traffic. My best guess for this would be that whichever DNS I'm using isn't configured for IPV6, and so sshuttle still intercepts the traffic.

**Comment by brianmay** [comment]
Hello,

You are correct.

As per documentation, sshuttle does not support intercepting IPv6 traffic unless running on Linux using the TPROXY method.

https://github.com/sshuttle/sshuttle/blob/master/README.rst

This is due to limitations in the underlying firewall implementations. e.g. on Linux the REDIRECT target is IPv4 only. (At least this was the case when I last researched this issue)

If you are using Linux you may be able to switch to using the TPROXY method (see above documentation), otherwise you could be out of luck.

Regards

**Comment by naclander** [comment]
I am on linux. So I attempted to follow the directions in the README.

I ran as root:

    ip route add local default dev lo table 100
    ip rule add fwmark 1 lookup 100
    ip -6 route add local default dev lo table 100
    ip -6 rule add fwmark 1 lookup 100

And after cloning the sshuttle repo I ran:

    sudo SSH_AUTH_SOCK="$SSH_AUTH_SOCK" ./run --method=tproxy --dns --no-latency-control -vv -r naclander@ssh.linux.ucla.edu 0/0 -x 10.0.0.0/24

which terminates with a:

    c : fatal: server died with error code 255

I'll keep trying to solve this issue.

**Comment by brianmay** [comment]
No, that doesn't look like point 4. Point 4 the client will refuse to talk IPv6 and fallback to IPv4. Maybe the documentation should be clarified here.

Something else is happening here - are you able to post more of the debug output? Looks like the server is prematurely exiting, and there should be a stack trace.

**Comment by naclander** [comment]
From the top level sshuttle working directory on commit 2b235331d06c90b2e42294fabddea3dc1d3176b9, I ran the following command:
````    
# sudo ./run --method=tproxy -vv -r naclander@sshserver 0/0
Python 3.5.1
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.5.1
firewall manager: ready method name tproxy.
UDP enabled: True
Binding redirector: 12300
TCP redirector listening on ('::1', 12300, 0, 0).
TCP redirector listening with <socket.socket fd=5, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 12300, 0, 0)>.
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
UDP redirector listening on ('::1', 12300, 0, 0).
UDP redirector listening with <socket.socket fd=8, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('::1', 12300, 0, 0)>.
UDP redirector listening on ('127.0.0.1', 12300).
UDP redirector listening with <socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 12300)>.
tproxy UDP support enabled.
Starting client with Python version 3.5.1
c : connecting to server...
c : executing: ['ssh', 'naclander@sshserver', '--', 'P=python3.5; $P -V 2>/dev/null || P=python; exec "$P" -c \'import sys; verbosity=2; exec(compile(sys.stdin.read(890), "assembler.py", "exec"))\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
server: assembling 'sshuttle' (7 bytes)
server: assembling 'sshuttle.cmdline_options' (27 bytes)
server: assembling 'sshuttle.helpers' (764 bytes)
server: assembling 'sshuttle.ssnet' (5508 bytes)
server: assembling 'sshuttle.hostwatch' (2307 bytes)
server: assembling 'sshuttle.server' (3046 bytes)
Starting server with Python version 2.7.3
 s: latency control setting = True
 s: available routes:
 s:   2/131.179.104.0/24
 s:  > channel=0 cmd=PING len=7 (fullness=0)
 s:  > channel=0 cmd=ROUTES len=19 (fullness=7)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=26/0)
 s:   Ready: 1 r=[] w=[5] x=[]
c : Connected.
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[11] x=[] (fullness=7/0)
c :   Ready: 3 r=[11] w=[11] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : mux wrote: 15/15
c : mux wrote: 15/15
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[] x=[] (fullness=14/0)
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=26/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 27/27
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=26/0)
c :   Ready: 3 r=[11] w=[] x=[]
c : <  channel=0 cmd=ROUTES len=19
firewall manager: Got subnets: [(2, 0, False, '0.0.0.0'), (2, 8, True, '127.0.0.0')]
firewall manager: Got nslist: []
firewall manager: Got ports: 12300,12300,0,0
firewall manager: Got udp: True
firewall manager: setting up.
firewall manager: setting up IPv6.
firewall manager: setting up IPv4.
>> iptables -t mangle -N sshuttle-m-12300
>> iptables -t mangle -F sshuttle-m-12300
>> iptables -t mangle -N sshuttle-d-12300
>> iptables -t mangle -F sshuttle-d-12300
>> iptables -t mangle -N sshuttle-t-12300
>> iptables -t mangle -F sshuttle-t-12300
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=0 cmd=PING len=7
 s:  > channel=0 cmd=PONG len=7 (fullness=26)
 s: <  channel=0 cmd=PONG len=7
 s: received PING response
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=0/0)
>> iptables -t mangle -I OUTPUT 1 -j sshuttle-m-12300
>> iptables -t mangle -I PREROUTING 1 -j sshuttle-t-12300
>> iptables -t mangle -A sshuttle-d-12300 -j MARK --set-mark 1
>> iptables -t mangle -A sshuttle-d-12300 -j ACCEPT
>> iptables -t mangle -A sshuttle-t-12300 -m socket -j sshuttle-d-12300 -m tcp -p tcp
>> iptables -t mangle -A sshuttle-t-12300 -m socket -j sshuttle-d-12300 -m udp -p udp
>> iptables -t mangle -A sshuttle-m-12300 -j RETURN --dest 127.0.0.0/8 -m tcp -p tcp
>> iptables -t mangle -A sshuttle-t-12300 -j RETURN --dest 127.0.0.0/8 -m tcp -p tcp
>> iptables -t mangle -A sshuttle-m-12300 -j RETURN --dest 127.0.0.0/8 -m udp -p udp
>> iptables -t mangle -A sshuttle-t-12300 -j RETURN --dest 127.0.0.0/8 -m udp -p udp
>> iptables -t mangle -A sshuttle-m-12300 -j MARK --set-mark 1 --dest 0.0.0.0/0 -m tcp -p tcp
>> iptables -t mangle -A sshuttle-t-12300 -j TPROXY --tproxy-mark 0x1/0x1 --dest 0.0.0.0/0 -m tcp -p tcp --on-port 12300
>> iptables -t mangle -A sshuttle-m-12300 -j MARK --set-mark 1 --dest 0.0.0.0/0 -m udp -p udp
>> iptables -t mangle -A sshuttle-t-12300 -j TPROXY --tproxy-mark 0x1/0x1 --dest 0.0.0.0/0 -m udp -p udp --on-port 12300
c : <  channel=0 cmd=PONG len=7
c : received PING response
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[] x=[] (fullness=0/0)
packet_write_wait: Connection to 131.179.104.17: Broken pipe
c :   Ready: 3 r=[11] w=[] x=[]
firewall manager: undoing changes.
firewall manager: undoing IPv6 changes.
firewall manager: undoing IPv4 changes.
>> iptables -t mangle -D OUTPUT -j sshuttle-m-12300
>> iptables -t mangle -F sshuttle-m-12300
>> iptables -t mangle -X sshuttle-m-12300
>> iptables -t mangle -D PREROUTING -j sshuttle-t-12300
>> iptables -t mangle -F sshuttle-t-12300
>> iptables -t mangle -X sshuttle-t-12300
>> iptables -t mangle -F sshuttle-d-12300
>> iptables -t mangle -X sshuttle-d-12300
firewall manager: undoing /etc/hosts changes.
c : fatal: server died with error code 255
````

**Comment by brianmay** [comment]
I believe 131.179.104.17 is the remote ssh server you are connecting to, right?

I suspect what is happening is that sshuttle is trying to intercept all packets, including the ssh connection itself. Try adding --exclude 131.179.104.17 to prevent intercepting the packets to the server.

**Comment by naclander** [comment]
yes ````131.179.104.17````  is the ip address of the remote server. Why would sshuttle try intercept the ssh connection packets in ````--method=tproxy```` only and not in the other methods?

When adding ```` --exclude 131.179.104.17```` I get an assertion error:
````
udo ./run --method=tproxy -vv --exclude 131.179.104.17 -r naclander@ssh.linux.ucla.edu 0/0       
Python 3.5.1
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.5.1
firewall manager: ready method name tproxy.
UDP enabled: True
Binding redirector: 12300
TCP redirector listening on ('::1', 12300, 0, 0).
TCP redirector listening with <socket.socket fd=5, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 12300, 0, 0)>.
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
UDP redirector listening on ('::1', 12300, 0, 0).
UDP redirector listening with <socket.socket fd=8, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('::1', 12300, 0, 0)>.
UDP redirector listening on ('127.0.0.1', 12300).
UDP redirector listening with <socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 12300)>.
tproxy UDP support enabled.
Starting client with Python version 3.5.1
c : connecting to server...
c : executing: ['ssh', 'naclander@ssh.linux.ucla.edu', '--', 'P=python3.5; $P -V 2>/dev/null || P=python; exec "$P" -c \'import sys; verbosity=2; exec(compile(sys.stdin.read(890), "assembler.py", "exec"))\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
server: assembling 'sshuttle' (7 bytes)
server: assembling 'sshuttle.cmdline_options' (27 bytes)
server: assembling 'sshuttle.helpers' (764 bytes)
server: assembling 'sshuttle.ssnet' (5508 bytes)
server: assembling 'sshuttle.hostwatch' (2307 bytes)
server: assembling 'sshuttle.server' (3046 bytes)
Starting server with Python version 2.7.3
 s: latency control setting = True
 s: available routes:
 s:   2/131.179.104.0/24
c : Connected.
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[11] x=[] (fullness=7/0)
c :   Ready: 3 r=[] w=[11] x=[]
c : mux wrote: 15/15
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[] x=[] (fullness=7/0)
 s:  > channel=0 cmd=PING len=7 (fullness=0)
 s:  > channel=0 cmd=ROUTES len=19 (fullness=7)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=26/0)
 s:   Ready: 1 r=[] w=[5] x=[]
c :   Ready: 3 r=[11] w=[] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : mux wrote: 15/15
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[] x=[] (fullness=14/0)
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=26/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 27/27
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=26/0)
c :   Ready: 3 r=[11] w=[] x=[]
c : <  channel=0 cmd=ROUTES len=19
firewall manager: Got subnets: [(2, 0, False, '0.0.0.0'), (2, 8, True, '127.0.0.0'), (2, 32, True, '131.179.104.17')]
firewall manager: Got nslist: []
firewall manager: Got ports: 12300,12300,0,0
firewall manager: Got udp: True
firewall manager: setting up.
firewall manager: setting up IPv6.
firewall manager: setting up IPv4.
>> iptables -t mangle -N sshuttle-m-12300
>> iptables -t mangle -F sshuttle-m-12300
>> iptables -t mangle -N sshuttle-d-12300
>> iptables -t mangle -F sshuttle-d-12300
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=0 cmd=PING len=7
 s:  > channel=0 cmd=PONG len=7 (fullness=26)
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=33/0)
>> iptables -t mangle -N sshuttle-t-12300
>> iptables -t mangle -F sshuttle-t-12300
>> iptables -t mangle -I OUTPUT 1 -j sshuttle-m-12300
 s:   Ready: 1 r=[4] w=[] x=[]
>> iptables -t mangle -I PREROUTING 1 -j sshuttle-t-12300
 s: <  channel=0 cmd=PONG len=7
 s: received PING response
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=0/0)
>> iptables -t mangle -A sshuttle-d-12300 -j MARK --set-mark 1
>> iptables -t mangle -A sshuttle-d-12300 -j ACCEPT
>> iptables -t mangle -A sshuttle-t-12300 -m socket -j sshuttle-d-12300 -m tcp -p tcp
>> iptables -t mangle -A sshuttle-t-12300 -m socket -j sshuttle-d-12300 -m udp -p udp
>> iptables -t mangle -A sshuttle-m-12300 -j RETURN --dest 131.179.104.17/32 -m tcp -p tcp
>> iptables -t mangle -A sshuttle-t-12300 -j RETURN --dest 131.179.104.17/32 -m tcp -p tcp
>> iptables -t mangle -A sshuttle-m-12300 -j RETURN --dest 131.179.104.17/32 -m udp -p udp
>> iptables -t mangle -A sshuttle-t-12300 -j RETURN --dest 131.179.104.17/32 -m udp -p udp
>> iptables -t mangle -A sshuttle-m-12300 -j RETURN --dest 127.0.0.0/8 -m tcp -p tcp
>> iptables -t mangle -A sshuttle-t-12300 -j RETURN --dest 127.0.0.0/8 -m tcp -p tcp
>> iptables -t mangle -A sshuttle-m-12300 -j RETURN --dest 127.0.0.0/8 -m udp -p udp
>> iptables -t mangle -A sshuttle-t-12300 -j RETURN --dest 127.0.0.0/8 -m udp -p udp
>> iptables -t mangle -A sshuttle-m-12300 -j MARK --set-mark 1 --dest 0.0.0.0/0 -m tcp -p tcp
>> iptables -t mangle -A sshuttle-t-12300 -j TPROXY --tproxy-mark 0x1/0x1 --dest 0.0.0.0/0 -m tcp -p tcp --on-port 12300
>> iptables -t mangle -A sshuttle-m-12300 -j MARK --set-mark 1 --dest 0.0.0.0/0 -m udp -p udp
>> iptables -t mangle -A sshuttle-t-12300 -j TPROXY --tproxy-mark 0x1/0x1 --dest 0.0.0.0/0 -m udp -p udp --on-port 12300
c : <  channel=0 cmd=PONG len=7
c : received PING response
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[] x=[] (fullness=0/0)
c :   Ready: 3 r=[7] w=[] x=[]
c : Accept TCP: 10.0.0.239:60710 -> 10.0.0.182:9091.
c :  > channel=1 cmd=TCP_CONNECT len=17 (fullness=0)
c : new channel: 1
c : Waiting: 4 r=[5, 7, 8, 9, 10, 11] w=[11] x=[] (fullness=17/0)
c :   Ready: 4 r=[10] w=[11] x=[]
c : mux wrote: 25/25
c :  > channel=1 cmd=TCP_DATA len=1596 (fullness=17)
c : Waiting: 4 r=[5, 7, 8, 9, 10, 11] w=[11] x=[] (fullness=1613/0)
c :   Ready: 4 r=[] w=[11] x=[]
c : mux wrote: 1604/1604
c : Waiting: 4 r=[5, 7, 8, 9, 10, 11] w=[] x=[] (fullness=1613/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=1 cmd=TCP_CONNECT len=17
 s: Connecting to 10.0.0.182:9091
 s: new channel: 1
 s: Waiting: 2 r=[4] w=[6] x=[] (fullness=0/0)
 s:   Ready: 2 r=[4] w=[] x=[]
 s: <  channel=1 cmd=TCP_DATA len=1596
 s: Waiting: 2 r=[4] w=[6] x=[] (fullness=0/0)
c :   Ready: 4 r=[7] w=[] x=[]
c : Accept TCP: 10.0.0.239:60716 -> 10.0.0.182:9091.
c :  > channel=2 cmd=TCP_CONNECT len=17 (fullness=1613)
c : new channel: 2
c : Waiting: 5 r=[5, 7, 8, 9, 10, 11, 12] w=[11] x=[] (fullness=1630/0)
c :   Ready: 5 r=[12] w=[11] x=[]
c : mux wrote: 25/25
c :  > channel=2 cmd=TCP_DATA len=1596 (fullness=1630)
c : Waiting: 5 r=[5, 7, 8, 9, 10, 11, 12] w=[11] x=[] (fullness=3226/0)
c :   Ready: 5 r=[] w=[11] x=[]
c : mux wrote: 1604/1604
c : Waiting: 5 r=[5, 7, 8, 9, 10, 11, 12] w=[] x=[] (fullness=3226/0)
 s:   Ready: 2 r=[4] w=[] x=[]
 s: <  channel=2 cmd=TCP_CONNECT len=17
 s: Connecting to 10.0.0.182:9091
 s: new channel: 2
 s: <  channel=2 cmd=TCP_DATA len=1596
 s: Waiting: 3 r=[4] w=[6, 7] x=[] (fullness=0/0)
c :   Ready: 5 r=[9] w=[] x=[]
c : Accept UDP: ('10.0.0.239', 59378) -> ('10.0.0.182', 53).
firewall manager: undoing changes.
firewall manager: undoing IPv6 changes.
firewall manager: undoing IPv4 changes.
>> iptables -t mangle -D OUTPUT -j sshuttle-m-12300
>> iptables -t mangle -F sshuttle-m-12300
>> iptables -t mangle -X sshuttle-m-12300
>> iptables -t mangle -D PREROUTING -j sshuttle-t-12300
>> iptables -t mangle -F sshuttle-t-12300
>> iptables -t mangle -X sshuttle-t-12300
>> iptables -t mangle -F sshuttle-d-12300
>> iptables -t mangle -X sshuttle-d-12300
firewall manager: undoing /etc/hosts changes.
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/naclander/Projects/sshuttle/sshuttle/__main__.py", line 216, in <module>
    opt.daemon, opt.pidfile)
  File "/home/naclander/Projects/sshuttle/sshuttle/client.py", line 645, in main
    seed_hosts, auto_nets, daemon)
  File "/home/naclander/Projects/sshuttle/sshuttle/client.py", line 488, in _main
    ssnet.runonce(handlers, mux)
  File "/home/naclander/Projects/sshuttle/sshuttle/ssnet.py", line 575, in runonce
    h.callback(s)
  File "/home/naclander/Projects/sshuttle/sshuttle/client.py", line 117, in <lambda>
    lambda sock: callback(sock, method, mux, handlers)
  File "/home/naclander/Projects/sshuttle/sshuttle/client.py", line 357, in onaccept_udp
    mux.send(chan, ssnet.CMD_UDP_OPEN, listener.family)
  File "/home/naclander/Projects/sshuttle/sshuttle/ssnet.py", line 369, in send
    assert isinstance(data, bytes)
AssertionError
c : SW#12:10.0.0.239:60716: deleting (3 remain)
c : SW'unknown':Mux#2: done writing
c :  > channel=2 cmd=TCP_EOF len=0 (fullness=3226)
c : SW'unknown':Mux#2: deleting (2 remain)
c : SW#10:10.0.0.239:60710: deleting (1 remain)
c : SW'unknown':Mux#1: done writing
c :  > channel=1 cmd=TCP_EOF len=0 (fullness=3226)
c : SW'unknown':Mux#1: deleting (0 remain)
````

**Comment by vieira** [comment]
This is fixed in PR #37

**Comment by naclander** [comment]
vieira,

I have rebased PR #37 on top of origin/master and I get the same assertion failure from the above post.

**Comment by vieira** [comment]
Hmm, that's weird because that assertion no longer exists with that PR. Instead there should be an assertion to binary_type that resolves to str in 2 and bytes in 3.

**Comment by naclander** [comment]
````
sudo ./run --method=tproxy -vv --exclude 131.179.104.17 -r naclander@ssh.linux.ucla.edu 0/0
Python 3.5.1
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 3.5.1
firewall manager: ready method name tproxy.
UDP enabled: True
Binding redirector: 12300
TCP redirector listening on ('::1', 12300, 0, 0).
TCP redirector listening with <socket.socket fd=5, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 12300, 0, 0)>.
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket.socket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 12300)>.
UDP redirector listening on ('::1', 12300, 0, 0).
UDP redirector listening with <socket.socket fd=8, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('::1', 12300, 0, 0)>.
UDP redirector listening on ('127.0.0.1', 12300).
UDP redirector listening with <socket.socket fd=9, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 12300)>.
tproxy UDP support enabled.
Starting client with Python version 3.5.1
c : connecting to server...
c : executing: ['ssh', 'naclander@ssh.linux.ucla.edu', '--', 'P=python3.5; $P -V 2>/dev/null || P=python; exec "$P" -c \'import sys, os; verbosity=2; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(937), "assembler.py", "exec"))\'']
c :  > channel=0 cmd=PING len=7 (fullness=0)
server: assembling u'sshuttle' (7 bytes)
server: assembling u'sshuttle.cmdline_options' (27 bytes)
server: assembling u'sshuttle.helpers' (949 bytes)
server: assembling u'sshuttle.ssnet' (5540 bytes)
server: assembling u'sshuttle.hostwatch' (2340 bytes)
server: assembling u'sshuttle.server' (3074 bytes)
Starting server with Python version 2.7.3
 s: latency control setting = True
 s: available routes:
 s:   2/131.179.104.0/24
 s:  > channel=0 cmd=PING len=7 (fullness=0)
c : Connected.
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[11] x=[] (fullness=7/0)
c :   Ready: 3 r=[] w=[11] x=[]
c : mux wrote: 15/15
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[] x=[] (fullness=7/0)
 s:  > channel=0 cmd=ROUTES len=19 (fullness=7)
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=26/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[5] x=[] (fullness=26/0)
 s:   Ready: 1 r=[] w=[5] x=[]
 s: mux wrote: 27/27
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=26/0)
c :   Ready: 3 r=[11] w=[] x=[]
c : <  channel=0 cmd=PING len=7
c :  > channel=0 cmd=PONG len=7 (fullness=7)
c : <  channel=0 cmd=ROUTES len=19
firewall manager: Got subnets: [(2, 0, False, '0.0.0.0'), (2, 8, True, '127.0.0.0'), (2, 32, True, '131.179.104.17')]
firewall manager: Got nslist: []
firewall manager: Got ports: 12300,12300,0,0
firewall manager: Got udp: True
firewall manager: setting up.
firewall manager: setting up IPv6.
firewall manager: setting up IPv4.
>> iptables -t mangle -N sshuttle-m-12300
>> iptables -t mangle -F sshuttle-m-12300
>> iptables -t mangle -N sshuttle-d-12300
>> iptables -t mangle -F sshuttle-d-12300
>> iptables -t mangle -N sshuttle-t-12300
>> iptables -t mangle -F sshuttle-t-12300
>> iptables -t mangle -I OUTPUT 1 -j sshuttle-m-12300
>> iptables -t mangle -I PREROUTING 1 -j sshuttle-t-12300
>> iptables -t mangle -A sshuttle-d-12300 -j MARK --set-mark 1
>> iptables -t mangle -A sshuttle-d-12300 -j ACCEPT
>> iptables -t mangle -A sshuttle-t-12300 -m socket -j sshuttle-d-12300 -m tcp -p tcp
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=0 cmd=PING len=7
 s:  > channel=0 cmd=PONG len=7 (fullness=26)
 s: mux wrote: 15/15
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=33/0)
>> iptables -t mangle -A sshuttle-t-12300 -m socket -j sshuttle-d-12300 -m udp -p udp
>> iptables -t mangle -A sshuttle-m-12300 -j RETURN --dest 131.179.104.17/32 -m tcp -p tcp
>> iptables -t mangle -A sshuttle-t-12300 -j RETURN --dest 131.179.104.17/32 -m tcp -p tcp
>> iptables -t mangle -A sshuttle-m-12300 -j RETURN --dest 131.179.104.17/32 -m udp -p udp
>> iptables -t mangle -A sshuttle-t-12300 -j RETURN --dest 131.179.104.17/32 -m udp -p udp
>> iptables -t mangle -A sshuttle-m-12300 -j RETURN --dest 127.0.0.0/8 -m tcp -p tcp
>> iptables -t mangle -A sshuttle-t-12300 -j RETURN --dest 127.0.0.0/8 -m tcp -p tcp
>> iptables -t mangle -A sshuttle-m-12300 -j RETURN --dest 127.0.0.0/8 -m udp -p udp
>> iptables -t mangle -A sshuttle-t-12300 -j RETURN --dest 127.0.0.0/8 -m udp -p udp
>> iptables -t mangle -A sshuttle-m-12300 -j MARK --set-mark 1 --dest 0.0.0.0/0 -m tcp -p tcp
>> iptables -t mangle -A sshuttle-t-12300 -j TPROXY --tproxy-mark 0x1/0x1 --dest 0.0.0.0/0 -m tcp -p tcp --on-port 12300
>> iptables -t mangle -A sshuttle-m-12300 -j MARK --set-mark 1 --dest 0.0.0.0/0 -m udp -p udp
>> iptables -t mangle -A sshuttle-t-12300 -j TPROXY --tproxy-mark 0x1/0x1 --dest 0.0.0.0/0 -m udp -p udp --on-port 12300
c : mux wrote: 15/15
c : <  channel=0 cmd=PONG len=7
c : received PING response
c : Waiting: 3 r=[5, 7, 8, 9, 11] w=[] x=[] (fullness=0/0)
 s:   Ready: 1 r=[4] w=[] x=[]
 s: <  channel=0 cmd=PONG len=7
 s: received PING response
 s: Waiting: 1 r=[4] w=[] x=[] (fullness=0/0)
c :   Ready: 3 r=[9] w=[] x=[]
c : Accept UDP: ('10.0.0.239', 58343) -> ('10.0.0.182', 53).
firewall manager: undoing changes.
firewall manager: undoing IPv6 changes.
firewall manager: undoing IPv4 changes.
>> iptables -t mangle -D OUTPUT -j sshuttle-m-12300
>> iptables -t mangle -F sshuttle-m-12300
>> iptables -t mangle -X sshuttle-m-12300
>> iptables -t mangle -D PREROUTING -j sshuttle-t-12300
>> iptables -t mangle -F sshuttle-t-12300
>> iptables -t mangle -X sshuttle-t-12300
>> iptables -t mangle -F sshuttle-d-12300
>> iptables -t mangle -X sshuttle-d-12300
firewall manager: undoing /etc/hosts changes.
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/naclandr/Projects/sshuttle/sshuttle/__main__.py", line 216, in <module>
    opt.daemon, opt.pidfile)
  File "/home/naclander/Projects/sshuttle/sshuttle/client.py", line 645, in main
    seed_hosts, auto_nets, daemon)
  File "/home/naclander/Projects/sshuttle/sshuttle/client.py", line 488, in _main
    ssnet.runonce(handlers, mux)
  File "/home/naclander/Projects/sshuttle/sshuttle/ssnet.py", line 583, in runonce
    h.callback(s)
  File "/home/naclander/Projects/sshuttle/sshuttle/client.py", line 117, in <lambda>
    lambda sock: callback(sock, method, mux, handlers)
  File "/home/naclander/Projects/sshuttle/sshuttle/client.py", line 357, in onaccept_udp
    mux.send(chan, ssnet.CMD_UDP_OPEN, listener.family)
  File "/home/naclander/Projects/sshuttle/sshuttle/ssnet.py", line 376, in send
    assert isinstance(data, binary_type)
AssertionError
````

**Comment by brianmay** [comment]
I also have a fix pending for this, which I just need to test. May also look at #37 too.

First for the easy part, @naclander asked "Why would sshuttle try intercept the ssh connection packets in --method=tproxy only and not in the other methods?"

For the NAT method we use the REDIRECT target. I believe this uses connection tracking. The ssh connection is established before we setup the firewall rules. So the REDIRECT sees packets from existing connections including the existing ssh connection and ignores them because it knows it can't deal with them. It only looks at new connections.

For the TPROXY method however we use a different set of rules, I suspect these rules don't use connection tracking; so they will stuff up existing connections too.

At least that is my theory.

**Comment by vieira** [comment]
PR #48 should fix the assertion error. You will still need to use --exclude until @brianmay pushes his fix.

**Comment by brianmay** [comment]
This should be fixed now. You will still need to use --exclude to ensure the firewall doesn't intercept packets it isn't suppose to intercept.

**Comment by naclander** [comment]
Unfortunately I am still experiencing the original issue.

Running the for commands in the tproxy section mentioned in 1. and then executing ````./run --method=tproxy --exclude 131.179.104.17 -vvr naclander@ssh.linux.ucla.edu 0/0````

I am still not seeing ipv6 packets being intercepted. ie,  ````icanhazip.com````  still show my real IPV6 address. 

This is run from the top level directory on commit 1e81bf3dfc125bab97a81c4070d7f95c7d2cf212

I can open up a new issue if that's easier to keep track of.

**Comment by brianmay** [comment]
You haven't specified any IPv6 routes.

Hmm. Probably not mentioned in the documentation. Add something like '::/0' to the end.

**Comment by naclander** [comment]
You were correct, appending ::/0 to the end of the above query does cause both IPV6 and IPV4 packets to be intercepted. So sshuttle seems to be working as it should. However it seems like I am getting no connection when trying IPV6, possibly because my remote server does not support IPV6.
