### ISSUE TITLE
OSError: [Errno 38] Socket operation on non-socket

### ISSUE THREAD

**Issue by vocuzi** [sshuttle/sshuttle#523]
Unable to use Mac as ssh server, no matter how I try using python. It shows this error : 
![fdsfsdfsdf](https://user-images.githubusercontent.com/21104691/93351753-b58d4900-f857-11ea-80ab-a4e73444ab12.png)

**Comment by brianmay** [comment]
You are using an older version that does not support Python 3.8. This is already fixed in the recent releases.

**Comment by vocuzi** [comment]
Installing it via pip fixed it for me. On ubuntu, while installing using apt I still get sshuttle version 0.78.5-1.
